# @name createResource
POST http://localhost:8080/test321432443
Content-Type: application/json

{
  "name": "test"
}

###
POST http://localhost:8080/test321432443
Content-Type: application/json

{
  "name": "test"
}

###
GET {{createResource.response.headers.Location}}

###
HEAD {{createResource.response.headers.Location}}

###
PUT {{createResource.response.headers.Location}}
Content-Type: application/json

{
  "name": "test 123"
}

###
GET {{createResource.response.headers.Location}}

###
DELETE {{createResource.response.headers.Location}}

###
HEAD {{createResource.response.headers.Location}}

###
GET {{createResource.response.headers.Location}}